UploadArquivoAula/Models/Arquivos.cs
namespace ArquivoDoc.Models
{
    public class Arquivos
    {
        public int Id { get; set; }
        public int Codigo { get; set; }
        public string Titulo { get; set; }
        public string Processo { get; set; }
        public string Categoria { get; set; }
        public string Descricao { get; set; }
        public byte[] Dados { get; set; }
        public string ContentType { get; set; }

    }
}

UploadArquivoAula/Models/ErrorViewModel.cs
using System;

namespace ArquivoDoc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UploadArquivoAula/Controllers/ArquivosController.cs
using ArquivoDoc.Infraestrutura;
using ArquivoDoc.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace ArquivoDoc.Controllers
{
    public class ArquivosController : Controller
    {
        private readonly ArquivoContext _arquivoContext;

        public ArquivosController(ArquivoContext arquivoContext)
        {
            _arquivoContext = arquivoContext;
        }

        public IActionResult Index()
        {
            var doc = _arquivoContext.Arquivos.ToList();
            return View(doc);
        }

        [HttpPost]
        public IActionResult CadastroDocumento(IList<IFormFile> arquivos, int codigo, string titulo, string categoria, string processo)
        {
            IFormFile imagemCarregada = arquivos.FirstOrDefault();
     
            if (ModelState.IsValid)
            {
                MemoryStream ms = new MemoryStream();
                imagemCarregada.OpenReadStream().CopyTo(ms);

                Arquivos arqui = new Arquivos()
                {
                    Codigo = codigo,
                    Titulo = titulo,
                    Processo = processo,
                    Categoria = categoria,
                    Descricao = imagemCarregada.FileName,
                    Dados = ms.ToArray(),
                    ContentType = imagemCarregada.ContentType
                };

                _arquivoContext.Arquivos.Add(arqui);
                _arquivoContext.SaveChanges();
            }

            TempData["AlertMessage"] = "Salvo com Sucesso...";
            return RedirectPermanent("https://localhost:44302/Home/Index");
        }
        
        public IActionResult Visualizar(int id)
        {
            var documentoBanco = _arquivoContext.Arquivos.FirstOrDefault(a => a.Id == id);

            return File(documentoBanco.Dados, documentoBanco.ContentType);
        }

        public IActionResult Apagar(int id)
        {
            if (ModelState.IsValid)
            {
                var ApagarDocumento = _arquivoContext.Arquivos.Where(x => x.Id == id).FirstOrDefaultAsync();

                _arquivoContext.Arquivos.Remove(ApagarDocumento.Result);
                _arquivoContext.SaveChanges();
            }

            TempData["Message"] = "Apagado com sucesso";
            return RedirectPermanent("https://localhost:44302/Arquivos");
        }
    }
}

UploadArquivoAula/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ArquivoDoc.Models;

namespace ArquivoDoc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UploadArquivoAula/Views/Arquivos/Index.cshtml
@model IEnumerable<ArquivoDoc.Models.Arquivos>
@{
    ViewData["Title"] = "Index";
}

@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["AlertMessage"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Processo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Processo)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Categoria)
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    <a asp-action="Visualizar" class="btn btn-info" asp-route-id="@item.Id" target="_blank">Vizualizar</a>
                    <a asp-action="Apagar" class="btn btn-danger" asp-route-id="@item.Id" target="_blank">Apagar</a>
                </td>
            </tr>
        }

    </tbody>
</table>

UploadArquivoAula/Views/Home/Index.cshtml
@model ArquivoDoc.Models.Arquivos

<h4>Cadastro</h4>
<hr />

@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-success">
       @TempData["AlertMessage"]
       <button type="button" class="close" data-dismiss="alert">
         <span>&times;</span>
       </button>
    </div>
}

<form action="/Arquivos/CadastroDocumento" enctype="multipart/form-data" method="post">
    <div class="form-group">
        <label asp-for="Codigo" class="control-label"></label>
        <input asp-for="Codigo" class="form-control" id="invalidCheck2" required />
        <span asp-validation-for="Codigo" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Titulo" class="control-label"></label>
        <input asp-for="Titulo" class="form-control" id="invalidCheck2" required />
        <span asp-validation-for="Titulo" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Categoria" class="control-label"></label>
        <input asp-for="Categoria" class="form-control" id="invalidCheck2" required />
        <span asp-validation-for="Categoria" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Processo" class="control-label"></label>
          <div class="input-group mb-3">
            <label asp-for="Processo" class="input-group-text" id="invalidCheck2" required for="inputGroupSelect01">Processo</label>
             <select asp-for="Processo" class="form-control" id="inputGroupSelect01">
                 <option value="1">Novo Processo</option>
                 <option value="2">Andamento</option>
                 <option value="3">Atualizado</option>
                <option value="4">Encerrado</option>
             </select>
             <span asp-validation-for="Processo" class="text-danger"></span>
          </div>
          <span asp-validation-for="Processo" class="text-danger"></span>
    </div>
    <div>
        <input type="file" name="arquivos" id="invalidCheck2" required />
    </div>
    <div>
        <br />
        <button class="btn btn-primary">Salvar</button>
    </div>
 </form>

UploadArquivoAula/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Cadastro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="Arquivos">Documentos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>